# Generated by Django 2.0.2 on 2018-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='owner',
            new_name='user',
        ),
    ]
