# Generated by Django 2.0.2 on 2018-02-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0002_rename_field_owner_on_filter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='label',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
