# Generated by Django 2.0.2 on 2018-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0003_filter_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='harvest',
        ),
        migrations.AddField(
            model_name='filter',
            name='active',
            field=models.BooleanField(default=False, help_text='Set active to harvest tweets.'),
            preserve_default=False,
        ),
    ]
