# Generated by Django 2.0.2 on 2018-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0004_rename_field_harvest_to_active_on_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='label',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
