# Generated by Django 2.0.2 on 2018-02-21 11:30

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0006_aggregationframework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('aggregationframework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chirp.AggregationFramework')),
                ('pipeline', jsonfield.fields.JSONField()),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('chirp.aggregationframework',),
        ),
    ]
