# Generated by Django 2.0.2 on 2018-02-21 11:46

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0007_aggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapReduce',
            fields=[
                ('aggregationframework_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chirp.AggregationFramework')),
                ('mapper', models.TextField(help_text='Enter valid JavaScript')),
                ('reducer', models.TextField(help_text='Enter valid JavaScript')),
                ('query', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Map/Reduce',
                'verbose_name_plural': 'Mappers/Reducers',
            },
            bases=('chirp.aggregationframework',),
        ),
    ]
