# Generated by Django 2.0.2 on 2018-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0008_mapreduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='aggregations',
            field=models.ManyToManyField(related_name='filters', to='chirp.AggregationFramework'),
        ),
    ]
