# Generated by Django 2.0.2 on 2018-02-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0010_add_fields_to_aggregationframework'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationframework',
            name='slug',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
