# Generated by Django 2.0.2 on 2018-02-22 14:58

import chirp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0014_aggregationframework_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationframework',
            name='js',
            field=chirp.fields.JavaScriptField(blank=True, null=True),
        ),
    ]
