# Generated by Django 2.0.2 on 2018-02-22 19:04

import chirp.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0015_aggregationframework_js'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregationframework',
            old_name='js',
            new_name='render_js',
        ),
        migrations.AddField(
            model_name='aggregation',
            name='pipeline_js',
            field=chirp.fields.JavaScriptField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapreduce',
            name='mapper_js',
            field=chirp.fields.JavaScriptField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapreduce',
            name='query_js',
            field=chirp.fields.JavaScriptField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapreduce',
            name='reducer_js',
            field=chirp.fields.JavaScriptField(blank=True, null=True),
        ),
    ]
