# Generated by Django 2.0.2 on 2018-02-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0018_remove_aggregation_pipeline_js'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregation',
            old_name='pipeline',
            new_name='pipeline_js',
        ),
    ]
