# Generated by Django 2.0.2 on 2018-02-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0019_rename_field_pipeline_on_aggregation_to_pipeline_js'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapreduce',
            name='mapper',
        ),
        migrations.RemoveField(
            model_name='mapreduce',
            name='query_js',
        ),
        migrations.RemoveField(
            model_name='mapreduce',
            name='reducer',
        ),
    ]
