# Generated by Django 2.0.2 on 2018-02-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0020_remove_fields_from_mapreduce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapreduce',
            old_name='query',
            new_name='query_js',
        ),
    ]
