# Generated by Django 2.0.2 on 2018-03-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0022_remove_aggregationframework_render_js'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregation',
            options={'verbose_name': 'Aggregation'},
        ),
        migrations.AlterModelOptions(
            name='aggregationframework',
            options={'ordering': ['title'], 'verbose_name': 'Aggregation', 'verbose_name_plural': 'Aggregations'},
        ),
    ]
