# Generated by Django 2.0.2 on 2018-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0023_change_meta_options_on_aggregationframework'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregationframework',
            name='query_field',
            field=models.CharField(blank=True, help_text='The name of the field used to drill-down results', max_length=32, null=True),
        ),
    ]
