# Generated by Django 2.0.2 on 2018-03-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0024_aggregationframework_query_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='sentiment_threshold',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Minimum value used to label tweets with positive/negative sentiment.', max_digits=2),
        ),
    ]
