# Generated by Django 2.0.2 on 2018-03-02 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0025_filter_sentiment_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='sentiment_threshold',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Minimum value used to label tweets with positive/negative sentiment.', max_digits=2, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(-1.0)]),
        ),
    ]
