# Generated by Django 2.0.2 on 2018-03-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0027_alter_field_sentiment_threshold_on_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregationframework',
            name='query_field',
            field=models.CharField(blank=True, help_text='The name of the field used to drill-down results', max_length=128, null=True),
        ),
    ]
