# Generated by Django 2.0.2 on 2018-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler', '0001_initial'),
        ('sessions', '0001_initial'),
        ('chirp', '0028_alter_field_query_field_on_aggregationframework'),
    ]
   
    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_access_token',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_access_token_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_key',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
