# Generated by Django 2.0.2 on 2018-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirp', '0029_load_aggregations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter_access_token',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_access_token_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_key',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_api_secret',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
